chore: convert project to typescript
Nona-Creative/nona-playground pull request #16
Opened 2020-11-15 20:00 UTC by jon-nona

## Scope

- PT-38 - convert iso-ts-react-native to typescript

## Work Done

- convert project to typescript
- update eslint rules for typescript
- add jest watch typeahead for better test filtering
- update outdated dependencies
- update bundling
- change init ios command to use npm package pod-install.
- fix start reset command to reset metro bundler

## Steps to Test

- pull the branch
- install the dependencies and install your pods
- run the app on android and ios and make sure you get the following screenshots

## Screenshot
<img width="427" alt="ScreenCapture at Sun Nov 15 21:58:25 SAST 2020" src="https://user-images.githubusercontent.com/42996940/99195331-b5dd8e00-278d-11eb-8713-4d12c46a6efa.png">

2020-11-20 05:27 UTC, neilrussell6 requested changes

2020-11-20 05:27 UTC, neilrussell6 commented on packages/mob-ui-react-native/index.js
> +import App from './src/modules/App/index'
why?

2020-11-20 05:27 UTC, neilrussell6 commented on packages/mob-ui-react-native/package.json
> +    "init:ios": "npx pod-install",
shouldn't need npx in npm script context if pod-install is a dep (can you add as dep)?

2020-11-20 05:27 UTC, neilrussell6 commented on packages/mob-ui-react-native/src/modules/App/App.component.tsx
> +const App: React.FunctionComponent<Record<string, unknown>> = () => (
in React we are using:
```
import React, { FC } from 'react'

const App: FC = () => (
```
is there nothing similarly simple in RN?

2020-11-20 06:44 UTC, jon-nona commented on packages/mob-ui-react-native/src/modules/App/App.component.tsx
> +const App: React.FunctionComponent<Record<string, unknown>> = () => (
@neilrussell6 FC is an alias of FunctionComponent? I just prefer the latter as it's more explicit, and I guess as far as typing the empty props interface goes, I can remove that if you want?

2020-12-01 09:07 UTC, neilrussell6 approved these changes

2020-12-01 09:42 UTC, merged