feat(Drawer component): initial
Nona-Creative/nona-playground pull request #4
Opened 2020-08-31 22:59 UTC by cameronolivier

Initial Drawer component and supporting libraries and code/utils.

2020-11-05 21:05 UTC, neilrussell6 requested changes

2020-11-05 21:05 UTC, neilrussell6 commented on packages/mob-ui-react-native/docs/components/roadmap.md
> +Components Roadmap
please move to ROADMAP.md in root

2020-11-05 21:05 UTC, neilrussell6 commented on packages/mob-ui-react-native/src/common/components/Drawer/Drawer.js
> +  ...props
please add trailing comma or install prettier and run :)

2020-11-05 21:05 UTC, neilrussell6 commented on packages/mob-ui-react-native/src/common/components/Drawer/Drawer.utils.js
> +import * as R from 'ramda'
please import functions individually

2020-11-05 21:05 UTC, neilrussell6 commented on packages/mob-ui-react-native/src/common/components/FloatingButton/FloatingButton.js
> +  ...props
please add trailing comma or run prettier

2020-11-05 21:05 UTC, neilrussell6 commented on packages/mob-ui-react-native/src/modules/App/App.utils.test.js
> +  import * as SUT from './App.utils'
please remove spaces

2020-11-05 21:05 UTC, neilrussell6 commented on packages/mob-ui-react-native/src/modules/DrawerExample/DrawerExample.js
> +import styles from './DrawerExample.styles'
please add newline between npm and local deps

2020-11-05 21:05 UTC, neilrussell6 commented on packages/mob-ui-react-native/src/modules/DrawerExample/DrawerExample.js
> +        <Text style={{fontStyle: 'italic', fontSize: 24, fontWeight: 'bold' }}>Peek-a-boo!</Text>
ideally we avoid any forms of personal expression and personality in the sample text we use :)
that is also descriptive eg.
eg.
```
<Text>DRAWER CONTENT</Text>
<Text>DRAWER CONTENT CHILDREN</Text>
```

2020-11-06 05:48 UTC, closed without merging

2020-11-06 06:37 UTC, cameronolivier commented on packages/mob-ui-react-native/src/common/components/Drawer/Drawer.utils.js
> +import * as R from 'ramda'
whhyyyyyy are we doing this? it's such a pain to use this way :/ (this is an offline discussion, I suppose... )

2020-11-06 06:37 UTC, cameronolivier commented on packages/mob-ui-react-native/src/modules/DrawerExample/DrawerExample.js
> +        <Text style={{fontStyle: 'italic', fontSize: 24, fontWeight: 'bold' }}>Peek-a-boo!</Text>
but it's cute. 


....ok ok I'll change it. Was more for the video Demo :D

2020-11-06 13:45 UTC, cameronolivier commented on packages/mob-ui-react-native/src/common/components/FloatingButton/FloatingButton.js
> +  ...props
there's no trailing comma with spreads :) (I have prettier running)