feat(react): add sentry and sentry middleware example
Nona-Creative/nona-playground pull request #9
Opened 2020-10-22 09:46 UTC by jon-nona

![](https://media.giphy.com/media/YWht0oD4mxNDO/giphy.gif)

## Scope

PT5 - Sentry - Redux Sentry Middleware

## Work Done

- Add Sentry and Redux Sentry Middleware to web-ui-react

## Steps to Test

- pull the branch
- create an environment file and add a Sentry DSN environment file.
- Cause an application error and check that it captures the redux application state in Sentry

2020-10-23 13:18 UTC, neilrussell6 requested changes

2020-10-23 13:18 UTC, neilrussell6 commented on docs/branch/iso__react__redux__middleware__sentry__redux-sentry-middleware.tpl.md
> +> Implements Sentry and Redux Sentry middleware for React
please add reference to the module used with a link eg.
```
Implements Sentry and Redux Sentry middleware for React using [redux-sentry-middleware](https://github.com/vidit-sh/redux-sentry-middleware)
```

2020-10-23 13:18 UTC, neilrussell6 commented on docs/branch/iso__react__redux__middleware__sentry__redux-sentry-middleware.tpl.md
> +[src/common/sentry/index.js](https://raw.githubusercontent.com/Nona-Creative/nona-playground/iso__react__redux__middleware__sentry__redux-sentry-middleware/packages/web-ui-react/src/common/redux/midd
please update this to:
```
[src/common/redux/middleware.js](...
```

2020-10-23 13:18 UTC, neilrussell6 commented on packages/web-ui-react/.env.tpl
> +REACT_APP_SENTRY_DSN=xxxxxxxx
please change to this:
```
REACT_APP_SENTRY_DSN=
```
this is the convention I am using everywhere else on the playground and I think is more common

2020-10-23 13:18 UTC, neilrussell6 commented on packages/web-ui-react/src/index.js
> -
please re-add this newline

2020-10-26 09:13 UTC, jon-nona commented on docs/branch/iso__react__redux__middleware__sentry__redux-sentry-middleware.tpl.md
> +> Implements Sentry and Redux Sentry middleware for React
@neilrussell6 this should be addressed now

2020-10-26 09:13 UTC, jon-nona commented on docs/branch/iso__react__redux__middleware__sentry__redux-sentry-middleware.tpl.md
> +[src/common/sentry/index.js](https://raw.githubusercontent.com/Nona-Creative/nona-playground/iso__react__redux__middleware__sentry__redux-sentry-middleware/packages/web-ui-react/src/common/redux/midd
done:)

2020-10-26 09:30 UTC, neilrussell6 approved these changes

2020-10-26 12:25 UTC, merged